# Generated by Django 2.2.5 on 2019-10-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_imag', models.ImageField(upload_to='')),
                ('food_type', models.CharField(max_length=30)),
                ('food_sold_num', models.IntegerField(default=0)),
                ('food_left_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=200)),
            ],
        ),
    ]
