# Generated by Django 2.2.5 on 2019-10-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks_info',
            name='drink_img',
        ),
        migrations.RemoveField(
            model_name='food_info',
            name='food_imag',
        ),
    ]
