# Generated by Django 2.2.5 on 2019-10-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0002_auto_20191004_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
