# Generated by Django 2.2.5 on 2019-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0003_user_info_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
