# Generated by Django 2.2.5 on 2019-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0005_food_info_food_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='food_imag',
            field=models.ImageField(height_field=100, upload_to='img', width_field=100),
        ),
    ]
