# Generated by Django 2.2.5 on 2019-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0006_auto_20191005_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.FloatField()),
                ('order_name', models.CharField(max_length=200)),
            ],
        ),
    ]
