# Generated by Django 2.2.5 on 2019-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
